#!/usr/bin/env bash
#
# Installation script for batch-pics.
#
# Copyright (C) 2020, 2022 Rafael Cavalcanti - rafaelc.org
# Licensed under GPLv3

set -euo pipefail

readonly script_dir="$(dirname "$(readlink -f "$0")")"

printf "Installing dependencies...\n"
sudo apt install -y imagemagick zenity

printf "Creating symlinks...\n"
ln -sf "$script_dir/bin/batch-pics" "$HOME/.local/bin"
ln -sf "$script_dir/share/batch-pics.nemo_action" "$HOME/.local/share/nemo/actions/"

